name: Build Bloodreaper Kernel

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-22.04 # Fixado no 22.04 para garantir compatibilidade máxima com o script do dev

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc zip curl git wget python3 gcc clang libssl-dev cpio gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

    - name: Download Proton Clang (Toolchain)
      run: |
        # O script do dev procura o toolchain em ~/tc/bin.
        git clone --depth=1 https://github.com/kdrag0n/proton-clang.git ~/tc

    - name: Run Developer build.sh
      run: |
        chmod +x build.sh
        bash build.sh
          
    - name: Upload Kernel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Bloodreaper-AnyKernel3-ZIP
        path: "*.zip"
