name: Build Bloodreaper Kernel

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest # Usando a máquina mais moderna (24.04/22.04)

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc zip curl git wget python3 gcc clang libssl-dev cpio gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

    - name: Download Azure Clang (Toolchain)
      run: |
        # O script do dev procura o toolchain em ~/tc/bin.
        # Vamos clonar o Azure Clang (moderno e estável) diretamente para lá.
        git clone --depth=1 https://gitlab.com/Panda-OS/azure-clang.git ~/tc

    - name: Run Developer build.sh
      run: |
        # O build.sh assume que a pasta do toolchain é ~/tc/bin, que acabamos de criar.
        chmod +x build.sh
        bash build.sh
          
    - name: Upload Kernel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Bloodreaper-AnyKernel3-ZIP
        # O build.sh gera um arquivo ZIP na raiz do projeto começando com "Kernel_BloodReaper_gta4l_"
        path: "*.zip"
